/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export const Shape02 = (props) => {
  const { nodes } = useGLTF('/models/shape-02.glb')
  const both = useRef()
  const ring1 = useRef()
  const ring2 = useRef()
  useFrame((state, delta) => {
    ring2.current.rotation.x += delta
    ring1.current.rotation.z -= 0.5 * delta
  })
  return (
    <group {...props} dispose={null} scale={2.5} rotation={[0, 1.2, 0]} ref={both}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        rotation={[Math.PI / 4, 0, 0]}
        ref={ring1}
      >
        <meshNormalMaterial />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        position={[0, 0, 0]}
        rotation={[2.36, 0, 0]}
        scale={0.98}
        ref={ring2}
      >
        <meshNormalMaterial />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/shape-02.glb')
