/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export const Shape04 = (props) => {
  const { nodes } = useGLTF('/models/shape-04.glb')
  const s4 = useRef()
  useFrame((state, delta) => {
    s4.current.rotation.x += delta
    s4.current.rotation.z -= 0.5 * delta
  })
  return (
    <group {...props} dispose={null} scale={2.5} rotation={[0, 1.2, 0]} ref={s4}>
      <mesh castShadow receiveShadow geometry={nodes.Cube.geometry}>
        <meshNormalMaterial />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/shape-04.glb')
