import * as THREE from 'three'
import React, { useRef, useEffect, useState, useMemo, Suspense, memo } from 'react'
import { applyProps, Canvas, useFrame } from '@react-three/fiber'
import styles from './styles.module.scss'
import {
  AccumulativeShadows,
  Backdrop,
  BakeShadows,
  Bounds,
  Center,
  Environment,
  Grid,
  Html,
  OrbitControls,
  Preload,
  RandomizedLight,
  Stage,
  useGLTF,
} from '@react-three/drei'
import { FlakesTexture } from 'three-stdlib'
import { useLayoutEffect } from 'react'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

function ContainerModel(props) {
  const { nodes, materials } = useGLTF('/models/gold-container-01.glb')
  useLayoutEffect(() => {
    applyProps(materials.Gold, {
      color: 'gold',
      roughness: 0.5,
      normalMap: new THREE.CanvasTexture(
        new FlakesTexture(99, 99),
        THREE.UVMapping,
        THREE.RepeatWrapping,
        THREE.RepeatWrapping,
      ),
      'normalMap-repeat': [4, 4],
      normalScale: [0.5, 0.5],
    })
  })
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube077.geometry}
        material={materials.Gold}
        scale={0.5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube069.geometry}
        material={materials.Gold}
        scale={0.5}
      />
      <group scale={0.5}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_1.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_2.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_3.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_4.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_5.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_6.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_7.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_8.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_9.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube071_10.geometry}
          material={materials.Steel}
        />
      </group>
      <group scale={0.5}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_1.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_2.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_3.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_4.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_5.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_6.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_7.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_8.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_9.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017_10.geometry}
          material={materials.Steel}
        />
      </group>
      <group scale={0.5}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials['Material.028']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_2.geometry}
          material={materials['Material.029']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_3.geometry}
          material={materials['Material.031']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_4.geometry}
          material={materials['Material.032']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_5.geometry}
          material={materials['Material.030']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_6.geometry}
          material={materials['Material.034']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_7.geometry}
          material={materials['Material.033']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_8.geometry}
          material={materials['Material.035']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_9.geometry}
          material={materials['Material.036']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_10.geometry}
          material={materials['Material.037']}
        />
      </group>
      <group scale={0.5}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105.geometry}
          material={materials.Steel}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105_1.geometry}
          material={materials['Material.040']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105_2.geometry}
          material={materials['Material.041']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105_3.geometry}
          material={materials['Material.042']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105_4.geometry}
          material={materials['Material.043']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105_5.geometry}
          material={materials['Material.044']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105_6.geometry}
          material={materials['Material.045']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105_7.geometry}
          material={materials['Material.046']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105_8.geometry}
          material={materials['Material.047']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105_9.geometry}
          material={materials['Material.048']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube105_10.geometry}
          material={materials['Material.049']}
        />
      </group>
    </group>
  )
}

export const StagedContainer = () => {
  const cRef = useRef()
  return (
    <>
      <Stage
        preset={'rembrandt'}
        shadows={{ type: 'accumulative', color: 'orange', colorBlend: 5, opacity: 1, offset: 0.05 }}
        adjustCamera={1.2}
        intensity={1}
      >
        <group ref={cRef}>
          <ContainerModel />
        </group>
      </Stage>
      <Preload all />
    </>
  )
}

export const SimplerContainer = () => {
  const cRef = useRef()
  return (
    <>
      <Center>
        <group ref={cRef}>
          <ContainerModel />
        </group>
      </Center>
      <Preload all />
    </>
  )
}

export default function Container() {
  return (
    <div className={styles.container}>
      <Canvas shadows camera={{ position: [-20, 10, 20], near: 0.02, far: 1000, fov: 10 }}>
        <Stage
          preset={'upfront'}
          shadows={{ type: 'accumulative', color: 'orange', colorBlend: 5, opacity: 1 }}
        >
          <ContainerModel rotation={[0, Math.PI, 0]} />
        </Stage>
        {/* <Grid
          infiniteGrid
          cellThickness={1}
          cellColor='white'
          args={[20, 20, 20, 20]}
          position={[0, 2.25, 0]}
          fadeDistance={10000}
        /> */}
        <Preload all />
        <OrbitControls
          autoRotate
          autoRotateSpeed={-0.25}
          zoomSpeed={0.25}
          dampingFactor={0.05}
          enablePan={false}
          enableZoom={false}
          enableRotate={false}
        />
      </Canvas>
    </div>
  )
}

useGLTF.preload('/models/gold-container-01.glb')
