import { GoogleSpreadsheet } from 'google-spreadsheet'

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).send({ message: 'Only POST requests allowed' })
  }

  const body = req.body
  const now = new Date()

  try {
    // Initialize the sheet - doc ID is the long id in the sheets URL
    const doc = new GoogleSpreadsheet(process.env.GOOGLE_SHEET_ID)

    // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
    await doc.useServiceAccountAuth({
      // env var values are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      private_key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
    })

    await doc.loadInfo() // loads document properties and worksheets
    // console.log(doc.title)

    const sheet = doc.sheetsByIndex[0] // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
    // console.log(sheet.title)
    // console.log(sheet.rowCount)

    const newRow = await sheet.addRow({ created: now, email: body.email })
    return res.status(201).json({
      data: newRow.data,
    })
  } catch (e) {
    return res.status(e.code).send({ message: e.message })
  }
}
